name: Authority Snapshot

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run bootstrap
        run: |
          chmod +x agent/bootstrap.sh
          ./agent/bootstrap.sh

      - name: Run snapshot script
        run: |
          chmod +x agent/snapshot_authority.sh
          ./agent/snapshot_authority.sh

      - name: Push changes
        run: git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
